[package]
name = "whipminer"
version = "0.1.0"
authors = ["Mehdi <mehdi_hsb@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
